version : "3.9"
services:
  nuxt:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - AUTH_ORIGIN=${AUTH_ORIGIN:-http://nuxt:3000}
      - AUTH_SECRET=${AUTH_SECRET}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - REPO_URL=${REPO_URL}
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://nuxt:3000/api/healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5  
    ports:
      - "3000:3000"

